context:
  version: 0.11.0

package:
  name: diskonaut
  version: ${{ version }}

source:
  url: https://github.com/imsnif/diskonaut/archive/${{ version }}.tar.gz
  sha256: 355367dbc6119743d88bfffaa57ad4f308596165a57acc2694da1277c3025928

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - diskonaut --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Terminal visual disk space navigator
  homepage: https://github.com/imsnif/diskonaut
  repository: https://github.com/imsnif/diskonaut

extra:
  recipe-maintainers:
    - danielnachun
